### ISSUE TITLE
Option to not make an image of the disk

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/ntfs2btrfs#1]
It would be nice if one was added.

**Comment by maharmstone** [comment]
Not going to happen - you can always delete it if you don't want it.

**Comment by MegaZeroX10** [comment]
What if there's not enough disk space to make the image?

**Comment by maharmstone** [comment]
You might want to read up on how `btrfs-convert` operates - we follow the same principles here.

**Comment by MegaZeroX10** [comment]
Does the image file get saved or not? I read the description and all it mentions is that it uses the free space to convert the drive.

**Comment by TheMadHau5** [comment]
The image file, much like the rest of btrfs, uses CoW (copy-on-write) and so doesn't use up much more additional hard disk space, so it should be fine keeping it there. As the author said, you could always delete it if you don't need it.
