### ISSUE TITLE
Wrong compression signature

### ISSUE THREAD

**Issue by sonicrules1234** [maharmstone/ntfs2btrfs#11]
Before the update, it was giving me that free space use chkdsk error on every ntfs partition I tried.  So I saw you made 2 commits and decided to try again.  It is the ntfs partition of a recent install of Windows 10 20H2.  The following is what happened:

[root@manjaro westly]# ntfs2btrfs /dev/sda5
Skipping overly large ADS \$Extend\$RmMetadata\$Repair:$Corrupt (2359296 > 16215)
Skipping overly large ADS \$Extend\$RmMetadata\$Repair:$Verify (716800 > 16216)
Skipping overly large ADS \$Extend\$RmMetadata\$TxfLog\$Tops:$T (1048576 > 16221)
Skipping overly large ADS \Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.Pb378ec07#\882818c534d0020bdc80236ecc332d62\Microsoft.PowerShell.ConsoleHost.ni.dll:WofCompressedData (347233 > 16206)
Skipping overly large ADS \Windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\66450953713be99c7f54d828732cb56c\PresentationCore.ni.dll:WofCompressedData (7111770 > 16206)
Skipping overly large ADS \Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.Ic1a2041b#\5cf24dafa411c166fcce8415916f973e\Microsoft.Isam.Esent.Interop.ni.dll:WofCompressedData (651969 > 16206)
Skipping overly large ADS \Windows\assembly\NativeImages_v4.0.30319_64\System.Servd1dec626#\15aac93fa4752b025fc8fe4628fac956\System.ServiceModel.Internals.ni.dll:WofCompressedData (468345 > 16206)
Skipping overly large ADS \Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.I0cd65b90#\fa21414c63b8c6a48d359248aa4c37bd\Microsoft.Isam.Esent.Interop.Wsa.ni.dll:WofCompressedData (573566 > 16206)
Compression signature was 4, expected 3.

**Comment by maharmstone** [comment]
Thanks for this, I'll try to reproduce. I've just pushed a patch which includes the filename if decompression fails - could you try it and let me know which file it is?

Also, if you have ntfs-3g installed, does that manage to read that file or not?

**Comment by sonicrules1234** [comment]
> Thanks for this, I'll try to reproduce. I've just pushed a patch which includes the filename if decompression fails - could you try it and let me know which file it is?
> 
> Also, if you have ntfs-3g installed, does that manage to read that file or not?

The file is Users/sonic/AppData/Local/Microsoft/OneDrive/logs/Personal/SyncEngine-2020-12-21.1635.8928.1.odlsent.  I have ntfs-3g installed.  I was able to copy the file to my home directly just fine. I used cat on it and as expected, it was binary data.

**Comment by maharmstone** [comment]
This is fixed in the latest version.

**Comment by sonicrules1234** [comment]
> This is fixed in the latest version.

Just tried the latest version.  It still gives me that error.
