### ISSUE TITLE
FTBFS on Fedora with non-x86_64 architectures

### ISSUE THREAD

**Issue by Conan-Kudo** [maharmstone/ntfs2btrfs#18]
I'm packaging `ntfs2btrfs` for Fedora, and I was caught by surprise by it [failing to build on all architectures other than x86_64](https://koji.fedoraproject.org/koji/taskinfo?taskID=63823733).

I've [restricted it to x86_64 only for now](https://src.fedoraproject.org/rpms/ntfs2btrfs/c/43e10d7e943fab9800e9a6e8e8d07c0f25172b2c), but it'd be nice if it could work on any architecture.

**Comment by maharmstone** [comment]
Thanks Neal. Could you please retry against the latest master? If it works, I'll release it as the latest version.

I think it's probably a good idea if you keep s390x masked though - I've not done any endian-proofing.

**Comment by Conan-Kudo** [comment]
[Seems like it works](https://koji.fedoraproject.org/koji/taskinfo?taskID=64283961)!

**Comment by maharmstone** [comment]
Excellent. I've released a new version today containing the fixes.
