### ISSUE TITLE
Converting a boot disk

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/ntfs2btrfs#2]
It would be nice if that was made possible. My suggestion is to have it add Quibble's EFI to the list of boot items and set it as default after converting the boot disk.

**Comment by maharmstone** [comment]
Not possible, due to how Windows is designed.

**Comment by MegaZeroX10** [comment]
1. Its not possible to convert it at the time that Windows runs chkdsk when the disk is in use?
2. Can the boot disk be converted by using a USB stick that has a WinRE/Linux distribution on it?

By the way, I was able to convert a Windows Server 2003 VHD to BTRFS (minus the messages regarding compressed inodes, which still show up on the disk instead of being deleted).

**Comment by maharmstone** [comment]
# If you want to write such a thing, be my guest.
# Yes - by "boot disk", I mean "current boot disk".

**Comment by MegaZeroX10** [comment]
What about opening this ticket and adding a help wanted label and then see if anyone helps add it?

**Comment by TheMadHau5** [comment]
1. Converting the current boot disk _shouldn't_ be recommended, or even allowed, for that matter. As for converting it pre-boot, that doesn't seem like a bad idea but it'd probably take quite a bit more effort to code.
2. WinRE would have to have btrfs support and a copy of the ntfs2btrfs executable. As for a linux usb, it should work if compiled.
