### ISSUE TITLE
create into subvolume

### ISSUE THREAD

**Issue by Schokokex** [maharmstone/ntfs2btrfs#20]
wouldnt it make sense to create the windows/ntfs root into a subvolume if possible?
Think about making a snapshot with the initial state, you tinker around and want to restore the snapshot. The beautiful way is to have the root filesystem as a manager for snapshots, holding nothing but the snapshot folders (including the active subvolume).
If we use the snapshots as is at the moment, you would set-default the initial snapshot or a copy of it. That leaves behind the root subvolume 5 filled with windows files, that are used.

current solution:
```
root (subvolume 5/set-default):
- snapshots - convertedWindows (readonly)
            - snapshot 20210101 (readonly)
            - snapshot 20210201 (readonly)
            - ...
- Users
- Windows
- ...
```
prefered way:
```
root (subvolume 5):
- current (set-default)
- convertedWindows (readonly)
- 20210101 (readonly)
- 20210201 (readonly)
- ...
```

**Comment by maharmstone** [comment]
I don't agree - if a file's in the root of the NTFS volume it should be in the root of the Btrfs volume.

If you want everything in another subvol, it's easy enough to do that manually after conversion...
