### ISSUE TITLE
Could not open d: (error 5).

### ISSUE THREAD

**Issue by axet** [maharmstone/ntfs2btrfs#25]
Using administrator. Windows 10. ntfs2btrfs-20210523-win

**Comment by keuin** [comment]
I also observed this. I am not sure if this is a feature or a bug, but using uppercase letter will solve this problem.

**Comment by maharmstone** [comment]
@keuin is right, this was caused by me stupidly not checking for lowercase drive letters. Fixed by https://github.com/maharmstone/ntfs2btrfs/commit/209d28bc917c6ab477ab31fa8607eaaa545ae82e.
