### ISSUE TITLE
Error when compiling.

### ISSUE THREAD

**Issue by alexandermeek** [maharmstone/ntfs2btrfs#28]
I'm on linux trying to build from source. Followed the instructions on the readme, including installing the libfmt package. 
When running the make command I got the following error:

ntfs2btrfs/src/compress.cpp:25:10: fatal error: lzo/lzo1x.h: No such file or directory
#include <lzo/lzo1x.h>

Am I missing a package? I have the liblzo2-2 package.

Any help would be appreciated.

**Comment by maharmstone** [comment]
Possibly. It doesn't ship a cmake file unfortunately, so there's no easy way to check you're missing it. The exact version I'm using is lzo 2.10.2 on Gentoo, if that helps.

**Comment by alexandermeek** [comment]
Got it to work, had to install the dev version since I only had liblzo 2.10.1. Also needed libzstd-dev.
