### ISSUE TITLE
Arch aur: /usr/sbin exists in filesystem (owned by filesystem)

### ISSUE THREAD

**Issue by gyurmogyuri** [maharmstone/ntfs2btrfs#30]
Hello!
I tried to install for arch. But I got the subject error. Do you have any idea? Thanks!

**Comment by maharmstone** [comment]
No idea, sorry - I've never used Arch. @nicman23?

**Comment by nicman23** [comment]
yeah sorry close this i ll reply in the aur

**Comment by nicman23** [comment]
fyi fixed the package

**Comment by maharmstone** [comment]
Ta
