### ISSUE TITLE
Is this a fault?

### ISSUE THREAD

**Issue by daiaji** [maharmstone/ntfs2btrfs#47]
```
sudo ntfs2btrfs  /dev/disk/by-id/nvme-P6F3840_SE19C11P7050835-part1 
Using Zstd compression.
Using CRC32C for checksums.
Processing inode 596892 / 596892 (100.0%)
Mapped 220431 inodes directly.
Rewrote 107690 inodes.
Inlined 93062 inodes.
Updating directory sizes
Calculating checksums 9713735 / 9713735 (100.0%)
/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = default_init_allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: IOT instruction  sudo ntfs2btrfs /dev/disk/by-id/nvme-P6F3840_SE19C11P7050835-part1
```

**Comment by jarrard** [comment]
/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = default_init_allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted

I get the above. I really don't know why the fix isn't put into master. 
Guess this project is a dead end if it isn't going to be maintained to at least work without needing users to go in and patch the source themselves!

**Comment by maharmstone** [comment]
I'm sick to the back teeth of this "bug". It's not even a bug, it's a false positive caused by one of the distros having the brilliant idea to compile things with debug assertions turned on. And it _is_ already fixed, or rather worked around, in master.

**Comment by jarrard** [comment]
Ok fair enough.  I couldn't get ntfs to btrfs to work for me either way.
