### ISSUE TITLE
ntfs2btrfs on windows doesn't print an explicit error when converting invalid disk drive

### ISSUE THREAD

**Issue by 13xforever** [maharmstone/ntfs2btrfs#55]
Running `ntfs2btrfs u:` (where u: doesn't exist) there's no user-visible error.
It would be helpful to be explicit in interactive mode, as not everyone can see errorlevel code.

![image](https://user-images.githubusercontent.com/36445/187071473-51b71c6f-27c6-4244-957d-1a9e4f85ce15.png)

**Comment by maharmstone** [comment]
I'm a bit confused what's going on here - you're right that this is what happens with the binaries I uploaded, but when I recompile it it works as intended. It's not a bug in the code.

I've replaced the binaries with newly compiled ones (https://github.com/maharmstone/ntfs2btrfs/releases/download/20220812/ntfs2btrfs-20220812.zip). Does that work any better?

**Comment by 13xforever** [comment]
yes, with updated binaries there's an error
![image](https://user-images.githubusercontent.com/36445/187076312-3c13f087-bad8-4eba-b096-078e033bc3cf.png)
