### ISSUE TITLE
Can't convert from Fedora (Nobara) 36

### ISSUE THREAD

**Issue by artav4** [maharmstone/ntfs2btrfs#56]
Hello,

I've tried to use ntfs2btrfs to convert my data drive (with my games & folder used by Windows for documents, downloads etc) on Fedora 36 (Nobara actually) with Gnome but when I am trying to execute the command I am facing this issue : 
```
Using Zstd compression.
Using CRC32C for checksums.
/usr/include/c++/12/bits/stl_vector.h:1122: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = default_init_allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

I cannot understand where it could come from.

**Comment by maharmstone** [comment]
This is the distro's fault in using compile flags they really shouldn't, but it's worked around in the latest version. You probably want to let your distro know their build is broken.
