### ISSUE TITLE
Convert BTRFS back to NTFS?

### ISSUE THREAD

**Issue by i2** [maharmstone/ntfs2btrfs#59]
Is there a way to convert BTRFS back to NTFS?

I think this would be good to have as a revert mechanisk if there is an issue with the whole installation and booting of Windows on BTRFS+Quibble.

**Comment by maharmstone** [comment]
Yes, `-r`

**Comment by eldonishere** [comment]
does this work without the backup image?

**Comment by maharmstone** [comment]
No
