### ISSUE TITLE
FIXME runtime error

### ISSUE THREAD

**Issue by isa-pp** [maharmstone/ntfs2btrfs#6]
when trying to run it on my NTFS partition I receive a ``FIXME - other mapping error``

**Comment by xieve** [comment]
Same here – running ntfs2btrfs on the live disk image of gparted (Debian). I think the filesystem (and the partition) were created by the Windows 10 installation routine (it's not a system partition, though). It could've also been gparted, I can't recall exactly. When trying to use the Windows version, the executable just exits without any output or visible effect after around 5s. Message actually says `FIXME - other mapping`.

**Comment by lpchaim** [comment]
> Same here – running ntfs2btrfs on the live disk image of gparted (Debian). I think the filesystem (and the partition) were created by the Windows 10 installation routine (it's not a system partition, though). It could've also been gparted, I can't recall exactly. When trying to use the Windows version, the executable just exits without any output or visible effect after around 5s. Message actually says `FIXME - other mapping`.
> 
> Edit: I tried to use the Windows version from Windows PE (c't Notfall-Windows 2020), so there definitely shouldn't have been any kind of continuous usage.

Seeing similar behavior here, originally tried from Windows 10 and got no output, then from a Manjaro install and got a few expected lines about files being skipped then `FIXME - other mapping`. The only perhaps additional info I can provide is my disk was definitely originally created under W10.

**Comment by jrcichra** [comment]
Having the same issue, I'm working with a Windows 10 VM in KVM. I booted up a Manjaro iso to compile and run ntfs2btrfs and got this error.

**Comment by maharmstone** [comment]
This should be fixed in today's version.
