### ISSUE TITLE
Unable to convert volume: FSCTL_LOCK_VOLUME failed (error 5, access denied)

### ISSUE THREAD

**Issue by fnfontana** [maharmstone/ntfs2btrfs#60]
**Windows Specifications:**
```
Windows 10 Pro
22H2
19045.2251
Windows Feature Experience Pack 120.2212.4180.0
```

**Installation Details:**
I have tried ntfs2btrfs using `scoop install ntfs2btrfs` and `scoop install ntfs2btrfs -g` with Administrator privileges.

**The Problem:**
When run the command `ntfs2btrfs f:\` or `ntfs2btrfs F:\` it throws the output: 
```
Using Zstd compression.
Using CRC32C for checksums.
FSCTL_LOCK_VOLUME failed (error 5, access denied.).
```

**Screen Capture:**
![cmd_hh5ifd9DAx](https://user-images.githubusercontent.com/8870142/205446590-d66cc9e2-f454-4112-b4ff-99f2ab505d95.png)
Note: The terminal is running with administrator privileges

**Additional Information**
- The size of the partition that I'm trying to convert to btrfs is 50 GB
- This is a new, freshly created partition that was formatted using MiniTool Partition Wizard v12.7
- I have written no data on it

**Comment by maharmstone** [comment]
I think this usually happens when something else is using the drive. You'll have to find out what else is using F:.

**Comment by fnfontana** [comment]
> I think this usually happens when something else is using the drive. You'll have to find out what else is using F:.

Yes! I have figured it out about an hour ago and came here to update you.

After terminate a lot of background processes, I suspect that ABService.exe (Aomei Backupper) or another storage related software like VeraCrypt or Montainduck was causing the issue.

Thank you for reply!

**Comment by maharmstone** [comment]
Great! Possibly we need a better error message then, "access denied" isn't all that helpful.

**Comment by TTimo** [comment]
FWIW if you end up here after running into this problem like me, I used LockHunter on the drive to see which processes where locking, pressed the 'Unlock It!' button and then I could execute the conversion command successfully.
