### ISSUE TITLE
Symlinked executable does not work

### ISSUE THREAD

**Issue by sitiom** [maharmstone/ntfs2btrfs#64]
Hi, I am trying to add ntfs2btrfs to Winget: https://github.com/microsoft/winget-pkgs/pull/94782. The manifest successfully installs, but the symlinked executable (`ntfs2btrfs.exe`) silently fails without any output:
![image](https://user-images.githubusercontent.com/56180050/215046182-cc650a63-a4bd-48d4-a1db-83f8d8de997e.png)

However, calling the executable directly works:
![image](https://user-images.githubusercontent.com/56180050/215047233-de05f630-94cd-41e9-a737-be2cd2101525.png)

Can you fix it so that the symlinked executable will try to resolve the dependencies on the actual executable directory? Thanks.

**Comment by maharmstone** [comment]
I'm linking to the DLLs normally, I'm not doing anything weird.

I don't know anything about winget, but I can't imagine that it doesn't handle DLLs. I think you either need to fix your YAML file, or add a dependency on zlib and lzo, assuming they're also winget packages.

**Comment by sitiom** [comment]
> but I can't imagine that it doesn't handle DLLs.

Indeed, it doesn't 😅

**Comment by maharmstone** [comment]
That's pretty poor!

**Comment by sitiom** [comment]
Yes, it seems like I can only add static portable builds to Winget in the meantime:
- https://github.com/microsoft/winget-cli/issues/2711

**Comment by sitiom** [comment]
Update: As of today, winget now handles DLLs as of version https://github.com/microsoft/winget-cli/releases/tag/v1.9.25180 🎉. I have created a new PR on winget-pkgs:

- https://github.com/microsoft/winget-pkgs/pull/196214
