### ISSUE TITLE
Add a option to disable ntfs backup?

### ISSUE THREAD

**Issue by mio-19** [maharmstone/ntfs2btrfs#65]
My partition doesn't have much free space and got an error saying no space left.
I assume that this tool requires at least about 50%  free space to keep original ntfs. Is it correct?

**Comment by maharmstone** [comment]
No, that's not right. The image file is reflinked with the rest of the data, the only decrease in free space will be due to metadata and compressed files. If you don't have enough space, you will need to free some before using this program.

**Comment by mio-19** [comment]
> No, that's not right. The image file is reflinked with the rest of the data, the only decrease in free space will be due to metadata and compressed files. If you don't have enough space, you will need to free some before using this program.

Forgot to mention that files on my partition were compressed by default. Is it possible to add a option to reflink compressed files too?

**Comment by maharmstone** [comment]
> Is it possible to add a option to reflink compressed files too?

No, because btrfs doesn't support LZNT1.
