### ISSUE TITLE
FreeDOS version?

### ISSUE THREAD

**Issue by ale5000-git** [maharmstone/ntfs2btrfs#67]
It is just an idea, but it would be very nice if there was a version of this project that can run under FreeDOS.
It would be very useful to convert the boot partition.

PS: Another idea would be to make FreeDOS bootable by Quibble, so one could boot FreeDOS and run Ntfs2btrfs directly from Quibble.

**Comment by maharmstone** [comment]
Any non-EFI adaptations of Quibble are out of scope of the project, I'm afraid, though you're welcome to fork it if you like.
