### ISSUE TITLE
Do not `mmap(2)` disk devices on FreeBSD

### ISSUE THREAD

**Issue by danfe** [maharmstone/ntfs2btrfs#69]
Currently, `class memory_map` which provides _mmap(2)_-based access for a device and the code using it are guarded with `#ifndef _WIN32`.  These bits should be excluded on FreeBSD as well (see [this discussion](https://forums.freebsd.org/threads/mmap-dev-ada-drive-or-partition.81393/) which gives some rationale as to why).

**Comment by maharmstone** [comment]
Thanks for this - fixed by https://github.com/maharmstone/ntfs2btrfs/commit/1e0115b7faf4b72a1c5757165874645cf03663cc. Thanks also for adding it to Ports.
