### ISSUE TITLE
Compiling in linux

### ISSUE THREAD

**Issue by jmacato** [maharmstone/ntfs2btrfs#7]
OS: Ubuntu 20.10

I tried compiling this on a live cd and installed `build-essential` and `cmake` but it fails and the error points to `fmt::fmt-header-only` thing. Any ideas?

**Comment by maharmstone** [comment]
Sorry, I forget to say that there's a dependency on libfmt - I've updated the README.

Try installing libfmt-dev, it should work then.

**Comment by jmacato** [comment]
sorry for not saying that i already tried to install libfmt-dev and still had errors :(

**Comment by huangz986** [comment]
modify CMakeLists.txt, change fmt::fmt-header-only to fmt::fmt
