### ISSUE TITLE
Convert a 3Gb drive almost full without a reflink copy


### ISSUE THREAD

**Issue by servimo** [maharmstone/ntfs2btrfs#75]
As says the title, is this possible? 
I think I have enough disk space, 624GiB, I will try.

**Comment by maharmstone** [comment]
Try it. If it can't continue because it runs out of space, it shouldn't corrupt your existing filesystem.

There's no option to suppress the reflink copy, but unless you have a lot of compressed files the overhead should only be a few megabytes.

**Comment by servimo** [comment]
Thank you for your response, I am in the middle of the calc of the checksums.

**Comment by servimo** [comment]
What do mean this message in dmesg: "BTRFS warning (device sde1): devid 1 physical 0 len 134217728 inside the reserved space"? it popup everytime I mounted it.

**Comment by servimo** [comment]
Yes, it's working.

**Comment by sskras** [comment]
> How to get rid of this message?

@servimo, I assume this would need a serious research, thorough testing and a lengthy rewrite of the code. Not going to happen soon, I gues (unless eg. you start paying Mark an equal salary=)

**Comment by maharmstone** [comment]
> Not going to happen soon, I gues

A perfectly sensible thing to write, and quite by chance completely wrong :-)

This is one of the things that version 20260810 fixes
