### ISSUE TITLE
Can't delete `image/ntfs.img`

### ISSUE THREAD

**Issue by RuiNtD** [maharmstone/ntfs2btrfs#76]
Hello. I can't seem to delete `image/ntfs.img` on Windows because it's owned by SYSTEM and won't let me take ownership.
```
> sudo rm E:\image\ntfs.img
Remove-Item: Access to the path 'E:\image\ntfs.img' is denied.
> sudo takeown /F E:\image\ntfs.img
ERROR: Access is denied.
```
![explorer_XjrfzQEmu3](https://github.com/maharmstone/ntfs2btrfs/assets/1149870/e9568e3d-96ea-412c-ad8f-2df78bdf4186)

**Comment by RuiNtD** [comment]
I've even tried opening a CMD as SYSTEM and deleting it from there. Still nothing...

**Comment by maharmstone** [comment]
I seem to remember that the `image` subvolume gets created readonly. Try toggling that flag first.

**Comment by RuiNtD** [comment]
I didn't even know that was a subvolume. That worked. Thanks.

Also, you may want to update the README. Lol

**Comment by maharmstone** [comment]
Thanks, I have done: https://github.com/maharmstone/ntfs2btrfs/commit/8c6782680ce96a0f39957b7fc9849189aafe58ae

**Comment by ransagy** [comment]
In my case it doesn't seem to have the flag, and i can't modify attributes or anything on it in any way i found. Am i supposed to do something with the subvolume first?
