### ISSUE TITLE
change partition type code from 0700 to 8300 when conversion is complete

### ISSUE THREAD

**Issue by udance4ever** [maharmstone/ntfs2btrfs#79]
this is probably more proactive so some 3rd party Windows disk utility doesn't attempt to do something funky to a converted BTRFS partition that continues to have a partition type code of 0700 (Microsoft basic data) after completed conversion.

Workaround is to go into `gdisk` and change the partition type code to "8300" (Linux filesystem)

**Comment by maharmstone** [comment]
I'm not going to change the partition type if the user hasn't asked for this. If it's causing actual problems with something I might do it as a workaround, but not until then.

**Comment by udance4ever** [comment]
yes, you’re correct, it doesn’t seem to have any side effects.

isn’t the goal of this utility to convert a partition from one type to another?

Shouldn’t the tool ensure the partition table be in sync with the completed task?
