### ISSUE TITLE
aur package

### ISSUE THREAD

**Issue by nicman23** [maharmstone/ntfs2btrfs#8]
hey i packaged it https://aur.archlinux.org/packages/ntfs2btrfs-git if you want mention it in readme or something

thanks a lot for your work, you made windows servers bearable

**Comment by maharmstone** [comment]
Thanks a lot for this - I've added the link to the README.

**Comment by TheMadHau5** [comment]
Just got the aur package added to chaotic-aur :)

**Comment by nicman23** [comment]
oh nice

**Comment by maharmstone** [comment]
Brilliant!
